export interface StaffGeneratedRf {
  rf_id: string;
  rf_type: string;
  rf_status: number;
  staff_id_created: string;
  staff_id_solved: string;
  staff_id_verified: string;
  hub_id: string;
  red_flagged_staff_id: string;
  reopen_flag: number;
  date_logged: string;
  date_solved: string;
  date_verified: string;
  comment_created: string;
  comment_solved: string;
  comment_verified: string;
  entity_id: string;
  image_name: string;
  app_version: string;
  imei: string;
  log_entity_id: string;
  solve_entity_id: string;
  category: string;
  solve_method: string;
  red_flag_id: string;
  system_risk_level: string;
  user_risk_level: string;
  presence_flag: string;
}
