name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  GKE_PROJECT: ${{ secrets.GKE_PROD_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  GKE_CLUSTER: agric-os-prod-v2
  GKE_ZONE: europe-west3-a
  DEPLOYMENT_NAME: portfolio-management-v2
  IMAGE: portfolio-management
  REGISTRY_HOSTNAME: gcr.io
  src: ./src
  main: .

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/524687905739/locations/global/workloadIdentityPools/oidc-pool/providers/oidc-provider'
        service_account: 'oidc-test@agri-os-prod.iam.gserviceaccount.com'

      # Add this step to print the access token for debugging purposes
    - name: Print Access Token
      run: |
        gcloud auth print-access-token

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Build
      run: |
        docker build -t "$REGISTRY_HOSTNAME"/"$GKE_PROJECT"/"$IMAGE":"$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" ./
      working-directory: ${{ env.main }}

    - name: Publish
      run: |
        docker push $REGISTRY_HOSTNAME/$GKE_PROJECT/$IMAGE:$GITHUB_SHA
      working-directory: ${{ env.main }}

    - name: Set up Kustomize
      run: |
        curl -o kustomize --location https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize
      working-directory: ${{ env.src }}

    # - id: 'get-credentials'
    #   uses: 'google-github-actions/get-gke-credentials@v1'
    #   with:
    #     cluster_name:  ${{ env.GKE_CLUSTER }}
    #     location: ${{ env.GKE_ZONE }}

    - name: Deploy
      run: |
        sed -i -e 's/REGISTRY_HOSTNAME/'"$REGISTRY_HOSTNAME"'/' ./infra/k8s/portfolio-management-depl.yaml
        sed -i -e 's/IMAGE/'"$IMAGE"'/' ./infra/k8s/portfolio-management-depl.yaml
        sed -i -e 's/GITHUB_SHA/'"$GITHUB_SHA"'/' ./infra/k8s/portfolio-management-depl.yaml
        ./kustomize build ./infra/k8s | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide
      working-directory: ${{ env.src }}
